# Generated by Django 5.2.8 on 2025-11-12 13:01

import django.db.models.deletion
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '财务类别',
                'verbose_name_plural': '财务类别',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('record_type', models.CharField(choices=[('expense', '支出'), ('income', '收入')], max_length=10, verbose_name='记录类型')),
                ('transaction_date', models.DateField(verbose_name='交易日期')),
                ('fund_manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='批准人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category', verbose_name='类别')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '财务记录',
                'verbose_name_plural': '财务记录',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ProofImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=finance.models.proof_image_upload_path, verbose_name='凭证图片')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_images', to='finance.financialrecord', verbose_name='财务记录')),
            ],
            options={
                'verbose_name': '凭证图片',
                'verbose_name_plural': '凭证图片',
            },
        ),
    ]
