# Generated by Django 5.2.8 on 2025-11-12 13:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目组名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目组描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('departments', models.ManyToManyField(related_name='project_groups', to='finance.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '项目组',
                'verbose_name_plural': '项目组',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='学号应为8-12位数字', regex='^\\d{8,12}$')], verbose_name='学号')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('grade_major', models.CharField(max_length=100, verbose_name='年级专业')),
                ('position', models.CharField(max_length=50, verbose_name='职位')),
                ('start_date', models.DateField(verbose_name='任职开始时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='任职结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('qq', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='QQ号应为5-15位数字', regex='^\\d{5,15}$')], verbose_name='QQ号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.department', verbose_name='所属部门')),
                ('project_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.projectgroup', verbose_name='项目组')),
            ],
            options={
                'verbose_name': '人员信息',
                'verbose_name_plural': '人员信息',
                'ordering': ['-is_active', 'department', 'position', 'name'],
                'indexes': [models.Index(fields=['department', 'is_active'], name='personnel_p_departm_c45b4b_idx'), models.Index(fields=['student_id'], name='personnel_p_student_5d98b3_idx')],
            },
        ),
    ]
