# Generated by Django 5.2.8 on 2025-11-12 12:47

import django.db.models.deletion
import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, verbose_name='类别描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '物品类别',
                'verbose_name_plural': '物品类别',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('description', models.TextField(blank=True, verbose_name='物品描述')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='序列号')),
                ('category', models.CharField(max_length=50, verbose_name='物品类别')),
                ('status', models.CharField(choices=[('available', '可用'), ('in_use', '使用中'), ('maintenance', '维护中'), ('damaged', '损坏'), ('lost', '丢失'), ('abandoned', '已弃用'), ('prohibited', '禁止借用')], default='available', max_length=20, verbose_name='物品状态')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='所有者')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=items.models.get_item_image_path, verbose_name='图片')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='图片描述')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否为主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item', verbose_name='物品')),
            ],
            options={
                'verbose_name': '物品图片',
                'verbose_name_plural': '物品图片',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='借用人姓名')),
                ('borrower_contact', models.CharField(default='NONE', max_length=100, verbose_name='借用人联系方式')),
                ('expected_return_time', models.DateTimeField(blank=True, null=True, verbose_name='预计归还时间')),
                ('start_time', models.DateTimeField(verbose_name='开始使用时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束使用时间')),
                ('purpose', models.CharField(max_length=200, verbose_name='使用目的')),
                ('notes', models.TextField(blank=True, verbose_name='使用备注')),
                ('is_returned', models.BooleanField(default=False, verbose_name='是否已归还')),
                ('condition_before', models.CharField(blank=True, max_length=200, verbose_name='使用前状况')),
                ('condition_after', models.CharField(blank=True, max_length=200, verbose_name='使用后状况')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='物品')),
            ],
            options={
                'verbose_name': '使用记录',
                'verbose_name_plural': '使用记录',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UsageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='usage_images/', verbose_name='图片')),
                ('image_type', models.CharField(choices=[('borrow', '借用时'), ('return', '归还时')], max_length=10, verbose_name='图片类型')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='图片描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.itemusage', verbose_name='使用记录')),
            ],
            options={
                'verbose_name': '使用记录图片',
                'verbose_name_plural': '使用记录图片',
                'ordering': ['-created_at'],
            },
        ),
    ]
