# Generated by Django 5.2.8 on 2025-11-12 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '备忘录',
                'verbose_name_plural': '备忘录',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memo_images/', verbose_name='图片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='图片描述')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memo.memo', verbose_name='备忘录')),
            ],
            options={
                'verbose_name': '备忘录图片',
                'verbose_name_plural': '备忘录图片',
            },
        ),
    ]
